web/apikeys/urls.py
from django.urls import path
from . import views

# Namespace name
app_name = 'apikeys_settings'

# Be careful setting the name to just /login use userlogin instead!
urlpatterns=[
    path('', views.index, name='index'),
]

web/editprofile/urls.py
from django.urls import path
from . import views

# Namespace name
app_name = 'edit_profile'

# Be careful setting the name to just /login use userlogin instead!
urlpatterns=[
    path('', views.index, name='index'),
]

web/projects/urls.py
from django.urls import path
from . import views

# Namespace name
app_name = 'projects'

# Be careful setting the name to just /login use userlogin instead!
urlpatterns=[
    path('', views.index, name='index'),
    path('<int:id>/delete/', views.delete_project,name='delete'),
    path('<int:id>/cancel/', views.cancel_scan,name='cancel'),
    path('<int:id>/backup/', views.DownloadBackup, name='backup'),
]

web/scans/urls.py
from django.urls import path
from django.contrib import admin
from . import views

# Namespace name
app_name = 'scans'

# Be careful setting the name to just /login use userlogin instead!
urlpatterns=[
     path('admin/', admin.site.urls),
    path('results/<int:number>', views.index, name='index'),
    path('new/', views.new_scan, name='new'),
]

web/web/urls.py
from django.urls import path,include
from django.contrib import admin
from django.views.generic import TemplateView
from rest_framework.authtoken.views import obtain_auth_token

from rest_framework_simplejwt.views import (
    TokenObtainPairView,
    TokenRefreshView,
)

from django.conf.urls.static import static
from django.conf import settings

from .views import MyTokenObtainPairView

from projects import views
from scans import views
from apikeys import views
from editprofile import views
from payments import views
from auth.views import DjangoReactObtainToken
from auth.views import sign_up

urlpatterns = [
    # path('', auth_views.LoginView.as_view(template_name='login.html'), name='login'),
    path('/admin/', admin.site.urls),
    path('',TemplateView.as_view(template_name='index.html')),
    path('api/payments/', include('payments.urls'), name='payments'),
    path('api/token/', DjangoReactObtainToken.as_view(), name='token_obtain_pair'),
    path('api/token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
    path('api/signup/', sign_up, name='sign_up'),
    # path('login/', auth_views.LoginView.as_view(template_name='login.html'), name='login'),
    # path('logout/', auth_views.LogoutView.as_view(template_name='logged_out.html'), name='logout'),
    path('api/projects/', include('projects.urls')),
    path('api/scans/', include('scans.urls')),
    path('api/schedules/', include('schedules.urls')),
    path('api/apikeys_settings/', include('apikeys.urls')),
    path('api/edit_profile/', include('editprofile.urls')),
    path('api/accounts/', include('accounts.urls')),

] 

web/editprofile/models.py
from django.db import models

class auth_user(models.Model):
    username = models.CharField(max_length=150)
    email = models.CharField(max_length=254)

    def __str__(self):
        return self.email

web/projects/models.py
from django.db import models
from accounts.models import Account

class Project(models.Model):
    number = models.PositiveSmallIntegerField(default=1)
    icon = models.ImageField(default=None, upload_to = 'static/img/target_icon')
    domain = models.CharField(max_length=300)
    last_change = models.DateTimeField(auto_now=False, blank=True,null=True,)
    STATUS_CHOICES = (("SCANNING", "Scanning"),("FINISHED", "Finished"),("WAITING","Waiting"))
    status = models.CharField(max_length=9, choices=STATUS_CHOICES, default='WAITING')
    command = models.CharField(max_length=400, unique=False, blank=True, null=True)
    scan_mode = models.CharField(max_length=400, unique=False, blank=True, null=True)
    user = models.ForeignKey(Account , on_delete=models.DO_NOTHING , null=True)
    # user = models.PositiveSmallIntegerField(null=True)

    def get_last_change(self):
        if self.last_change:
            return self.last_change.strftime('%d/%m/%Y - %H:%M')

        return self.last_change.strftime('%d/%m/%Y %H:%M')

    def __str__(self):
        return self.domain
    
    

web/editprofile/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.contrib.auth.hashers import make_password
from django.core.files.storage import FileSystemStorage
from .imgUser import imgUser
import os
from rest_framework.decorators import api_view
from rest_framework.response import Response
from rest_framework.decorators import api_view, permission_classes
from rest_framework.permissions import IsAuthenticated



def edit(request):
    response = "change made!"

    username = request.user
    dbUser = User.objects.get(username=username)

    post = request.data


    if 'username' in post:
        if dbUser.username != post['username']:
            dbUser.username = post['username']



    if 'email' in post:
        if dbUser.email != post['email']:
            dbUser.email = post['email']




    if 'CurrentPassword' in post and 'NewPassword' in post and 'ConfirmPassword' in post:
        if post['CurrentPassword'] != "" and post['NewPassword'] != "" and post['ConfirmPassword'] != "":
            CurrentPassword = post['CurrentPassword']

            if dbUser.check_password(CurrentPassword):
                if post['NewPassword'] == post['ConfirmPassword']:
                    dbUser.set_password(post['NewPassword'])
                else:
                    response = "new password and confirmation password are different!"
            else:
                response = "Current password wrong!"





    if 'UserPicture' in request.FILES:
        path = "static/imgUsers/img"+str(request.user.id)+".png"

        if os.path.exists(path):
            os.remove(path)

        myfile = request.FILES['UserPicture']
        fs = FileSystemStorage()
        filename = fs.save(path, myfile)



    if 'RemoveImg' in post:
        if post['RemoveImg'] == 'on':
            imagePath = "static/imgUsers/img" + str(dbUser.id) + ".png"

            if os.path.exists(imagePath):
                os.remove(imagePath)

            
        

    dbUser.save()
    

    return post['username'], response 
 

# @login_required(login_url='/login/')
@api_view(['POST'])
@permission_classes([IsAuthenticated])
def index(request):

    if request.method == "POST":
        username, response = edit(request)
    
    else:
        username = request.user
        response = ""
    print(request.data)
    print(request.user) 

    # dbUser = User.objects.get(username=username)

    
    # email = dbUser.email

    # imagePath = imgUser(request.user.id)

    # context = {
    #     "imagePath": imagePath,
    #     'UserName': username, 
    #     'email': email,
    #     'response': response,
    #     }
        
    # return render(request, "edit_profile.html", context)
    if response == 'change made!':
        return Response(response)
    else:
        return Response(response, status=400)

web/projects/views.py
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponse
from rest_framework.response import Response
# from .serializers import ProjectSerializer
from rest_framework.decorators import api_view, permission_classes,authentication_classes
from rest_framework.permissions import IsAuthenticated
from projects.models import Project
from django.core.files.base import ContentFile
from django.shortcuts import redirect
from django.contrib.auth.decorators import login_required
from django.utils import timezone
from schedules.views import deleteScheduleFromId
from editprofile.imgUser import imgUser
from schedules.views import timezone
from web.settings import BASE_DIR
import shutil, os, time, requests, favicon
from pathlib import Path
from subprocess import Popen
import zipfile
from rest_framework import status
import csv

from rest_framework.serializers import ModelSerializer

class ProjectSerializer(ModelSerializer):
    class Meta:
        model = Project
        fields = '__all__'




# Main Projects Page
# @login_required(login_url='/login/')
@api_view(['GET'])
@permission_classes([IsAuthenticated])
def index(request):

    imagePath = imgUser(request.user.id)

    timezones = timezone()

    projects_output = Project.objects.filter(user=request.user.id)
    db_projects_count = Project.objects.values('domain').count() or 0
    
    path = Path(__file__).resolve().parent.parent.parent / "Recon/"

    files_sorted_by_date = []
    final_date = []
    number_count = 0
    
    print("Path da pasta Recon: " + str(path))

    '''
    Case 'Recon' folder is not created, just load the page without any data.
    '''

    if not path.exists():
        context = {'projects_output':projects_output, "imagePath": imagePath, "timezones":timezones}
        return Response({
            'message' : 'Recon folder is not created yet. Try to running a scan',
            'status' : 404,
        })
    elif path.exists():
        # Sort Archives by Creation Date
        archives_parsed = sorted(Path(path).iterdir(), key=os.path.getmtime)
        
        print(archives_parsed)

        for archives in archives_parsed:
            archives_by_date = str(archives).split('/')[-1]
            files_sorted_by_date.append(archives_by_date)
            print(files_sorted_by_date)

        # Get Domain and Creation Date
        if db_projects_count != int(len(files_sorted_by_date)):
            for i in range(len(files_sorted_by_date)):
                sgdomain = files_sorted_by_date[i]
                print("SGDOMAIN: "+str(sgdomain))

                ti_m = os.path.getmtime(path / sgdomain)
                m_ti = time.ctime(ti_m)
                t_obj = time.strptime(m_ti)
                T_stamp = time.strftime("%Y-%m-%d %H:%M:%S", t_obj)
            
                print("T_stamp: "+str(T_stamp))

                final_date.append(T_stamp)

                print("final_date: "+str(final_date))

                pjtfor = Project.objects.filter(domain=sgdomain)
                # print("pjt: "+str(pjtfor))


                # Save Domain
                for pjt in pjtfor:
                    if not projects_output.filter(domain=pjt, number=pjt.number).exists():
                        print("number_count: " +str(number_count))
                        # pjt.save()

                    # Creation Date    
                    if not projects_output.filter(last_change = final_date[i], number=pjt.number):    
                        # pjt.last_change = final_date[i]
                        print("SALVOU FINAL_DATE["+str(i)+"]: "+str(final_date[i]))
                        
                        # pjt.save()


                    # Number of Projects
                    project_count_obj = pjt
                    
                    print("project_count_obj: "+str(project_count_obj))
            
        
        # GET ICONS
            for i in range(len(files_sorted_by_date)):
                sgdomain = files_sorted_by_date[i]
                
                target_iconfor = Project.objects.filter(domain=sgdomain)
                for target_icon in target_iconfor:
                    puredomain = str(target_icon).split('.')[0]+str(target_icon.number)

                    name_icon = puredomain+".ico"
                    
                    if not Project.objects.filter(icon = "static/img/target_icon/"+puredomain+".ico", number=target_icon.number).exists():
                        try:
                            try:
                                icon_url = favicon.get('http://www.'+str(target_icon))
                                if not icon_url:
                                    target_icon.icon.name = 'static/img/unknown.ico'
                                    print("NAO EXISTE ICONE: " +str(puredomain))
                                    print()
                                    target_icon.save()
                                
                                else:
                                    icon = icon_url[0]
                                    print("ICON URL: "+str(icon_url))

                                    response = requests.get(icon.url, stream=True, timeout=10)



                                    if response.status_code  == 200:
                                        target_icon.icon.save(name_icon, ContentFile(response.content), save=True)
                                        print("SALVANDO ICONE: "+name_icon)
                                    else:
                                        target_icon.icon.name = 'static/img/unknown.ico'
                                        print("DIFERENTE DE 200: " +puredomain)
                                        target_icon.save()

                            except (requests.exceptions.ConnectionError,requests.exceptions.HTTPError): 
                                target_icon.icon.name = 'static/img/unknown.ico'
                                print("ERROR: " +puredomain)
                                target_icon.save()
                        except (requests.exceptions.ReadTimeout):
                            print(target_icon.icon.name)
                            
                    else:
                        print("ICON ALREADY EXISTS: "+ name_icon)
                print("----------------------------------------------------------------------")

            else:
                print("EVERYTHING UP")
        
        # Project Number
        for u in range(len(files_sorted_by_date)):
            sgdomain = files_sorted_by_date[u]
            number_count = number_count + 1

            project_count_objfor = Project.objects.filter(domain=sgdomain)
            
            for project_count_obj in project_count_objfor:
                project_count_obj.project_number = number_count
                project_count_obj.save()

                print("ID NUMBER: "+ str(project_count_obj.project_number)+" [DOMAIN]: "+str(project_count_obj))
            

        context = {'projects_output':projects_output, "imagePath": imagePath, "timezones":timezones}
        
        

        projectSerialized= ProjectSerializer(projects_output, many=True)


        return Response({ "projects_output": projectSerialized.data, "imagePath": imagePath, "timezones":timezones}, status=status.HTTP_200_OK)
        # return render(request, 'projects.html',context)




# Delete Projects Function
# @login_required(login_url='/login/')
@api_view(['DELETE', 'GET'])
@permission_classes([IsAuthenticated])
def delete_project(request, id):

    target = Project.objects.get(id=id)
    if target:
        print("Project exists")
        project = get_object_or_404(Project, id=id)
        puredomain = str(project.icon).split('.')[0]

        command = str(project.command).split("'")
        del command[0::2]
        
        # if project.status != 'FINISHED':
        #     cancel_scan(request, id)

        if os.path.exists(command[-1]):
            path_projects_delete = command[-1]
        elif os.path.exists(f"{BASE_DIR.parent}/Recon/{str(project)}"): 
            path_projects_delete = f"{BASE_DIR.parent}/Recon/{str(project)}"
        else:
            path_projects_delete = "xxx"

        path_icon_delete = str(puredomain)+".ico"

        try:
            shutil.rmtree(path_projects_delete, ignore_errors=True)
            os.remove(path_icon_delete)
            print(path_icon_delete)
        except OSError as e:
            print("Error: %s - %s." % (e.filename, e.strerror))

        Project.objects.filter(id=id).delete()
        # deleteScheduleFromId(request, id=id)
        print("Project Deleted")

        # return redirect('projects:index')
        return Response({'message':"Project Deleted"}, status=status.HTTP_200_OK)
    else :
        return Response({'message':"Project Not Found"}, status=status.HTTP_404_NOT_FOUND)
# @login_required(login_url='/login/')



@api_view(['Get'])
# @permission_classes([IsAuthenticated]) 
def DownloadBackup(request, id):
    print('id ' , id)
    print(request.user)
    project = Project.objects.get(id=id)
    print(project.status)
    if project.status == "FINISHED":
        command = str(project.command).split("'")
        del command[0::2]

        tempFolder = "/tmp"
        folderPath = command[-1].rsplit("/",1)[0]
        folderName = command[-1].rsplit("/",1)[1]

        if "/" in folderName:
            tmp = folderName.rsplit("/", 1)

            folderPath = tmp[0]
            folderName = tmp[1]

        if os.path.exists(tempFolder+"/Backup-"+folderName+".zip"):
            os.remove(tempFolder+"/Backup-"+folderName+".zip")

        os.chdir(folderPath)

        with zipfile.ZipFile(tempFolder+"/Backup-"+folderName+".zip", "w") as zf:
            for item in Path(folderName).rglob("*"):
                print("item -> ", item)
                zf.write(item)
            zf.close()

        backupFileName = "Backup-"+folderName+".zip"

        file = open(tempFolder+"/"+backupFileName, "rb")

web/templates/logged_out.html
{% extends 'base.html' %} {% block title %}ReconFTW - See you!{% endblock %} {%
block content %}
<script>
  window.location.href = "{% url 'login' %}";
</script>
{% endblock %}

web/templates/scans_subdomains.html
{% extends 'base.html' %}
{% load static %}
{% block title %}reconFTW - Results{% endblock %}
{% block content %}

{% block extra_css %}
<link rel="stylesheet" href="{% static 'css/subdomains.css' %}">
{% endblock %}

{% include 'modal.html' %}


<body>

  <div class="contentDiv" id="content">
    <button class="back-to-top" type="button"></button>
  </div>

  <div class="sidebar close">
    <div class="logo-details">
      <img class="rftw-logo" src="/static/img/favicon.ico" alt="" />
      <span class="logo_name"> reconFTW</span>
    </div>

    <hr class="nav-hr" />

    <ul class="nav-links">
      <li>
        <a href="#section-1">
          <i class="bx bx-globe"></i>
          <span class="link_name">Subdomains</span>
        </a>
        <ul class="sub-menu blank">
          <li><a class="link_name" href="#section-1">Subdomains</a></li>
        </ul>
      </li>

      <li>
        <a href="#section-2">
          <i class="bx bx-cloud"></i>
          <span class="link_name">Cloud Assets</span>
        </a>
        <ul class="sub-menu blank">
          <li><a class="link_name" href="#section-2">Cloud Assets</a></li>
        </ul>
      </li>

      <li>
        <a href="#section-3">
          <i class="bx bx-image"></i>
          <span class="link_name">Screenshots</span>
        </a>
        <ul class="sub-menu blank">
          <li><a class="link_name" href="#section-3">Screenshots</a></li>
        </ul>
      </li>

      <li class="disabled_background">
        <a href="#" class="disabled">
          <i class="bx bx-search-alt disabled"></i>
          <span class="link_name_disabled">OSINT Output</span>
        </a>
        <ul class="sub-menu blank">
          <li><a class="disabled" href="#">OSINT Output</a></li>
        </ul>
      </li>

      <li class="disabled_background">
        <!-- <div class="disabled_background"> -->
          <a href="#" class="disabled">
            <i class="bx bx-ghost disabled"></i>
            <span class="link_name_disabled">Nuclei Output</span>
          </a>
          <i class="bx bxs-chevron-down arrow"></i>
        <!-- </div> -->
        <ul class="sub-menu">
          <li><a class="disabled" href="#">Nuclei Output</a></li>
          <li><a href="#" class="disabled">Info</a></li>
          <li><a href="#" class="disabled">Low</a></li>
          <li><a href="#" class="disabled">Medium</a></li>
          <li><a href="#" class="disabled">High</a></li>
          <li><a href="#" class="disabled">Critical</a></li>
        </ul>
      </li>

      <li class="disabled_background">
        <!-- <div class="disabled_background"> -->
          <a href="#" class="disabled">
            <i class="bx bx-bug disabled"></i>
            <span class="link_name_disabled">Vulnerabilities</span>
          </a>
          <i class="bx bxs-chevron-down arrow"></i>
        <!-- </div> -->
        <ul class="sub-menu">
          <li><a class="disabled" href="#">Vulnerabilities</a></li>
          <li><a href="#" class="disabled">Cors</a></li>
          <li><a href="#" class="disabled">Broken Links</a></li>
          <li><a href="#" class="disabled">smuggling</a></li>
          <li><a href="#" class="disabled">Command Injection</a></li>
          <li><a href="#" class="disabled">Open Redirect</a></li>
          <li><a href="#" class="disabled">SSRF</a></li>
          <li><a href="#" class="disabled">CRLF</a></li>
          <li><a href="#" class="disabled">XSS</a></li>
          <li><a href="#" class="disabled">LFI</a></li>
          <li><a href="#" class="disabled">SQLI</a></li>
          <li><a href="#" class="disabled">SSTI</a></li>
          <li><a href="#" class="disabled">GF Output</a></li>
        </ul>
      </li>

      <li class="disabled_background">
        <a href="#" class="disabled">
          <i class="bx bxs-folder-open disabled"></i>
          <span class="link_name_disabled">Fuzzing Paths</span>
        </a>
        <ul class="sub-menu blank">
          <li><a class="disabled" href="#">Fuzzing Paths</a></li>
        </ul>
      </li>

      <li class="disabled_background">
        <!-- <div class="disabled_background"> -->
          <a href="#" class="disabled">
            <i class="bx bxl-javascript disabled"></i>
            <span class="link_name_disabled">Javascript</span>
          </a>
          <i class="bx bxs-chevron-down arrow"></i>
        <!-- </div> -->
        <ul class="sub-menu">
          <li><a class="disabled" href="#">JavaScript</a></li>
          <li><a href="#" class="disabled">Endpoints</a></li>
          <li><a href="#" class="disabled">Links</a></li>
          <li><a href="#" class="disabled">Secrets</a></li>
        </ul>
      </li>

      <li class="disabled_background">
        <!-- <div class="disabled_background"> -->
          <a href="#" class="disabled">
            <i class="bx bxs-file disabled"></i>
            <span class="link_name_disabled">Dictionaries</span>
          </a>
          <i class="bx bxs-chevron-down arrow"></i>
        <!-- </div> -->
        <ul class="sub-menu">
          <li><a class="disabled" href="#">Dictionaries</a></li>
          <li><a href="#" class="disabled">Params</a></li>
          <li><a href="#" class="disabled">Values</a></li>
          <li><a href="#" class="disabled">Words</a></li>
          <li><a href="#" class="disabled">Paths</a></li>
        </ul>
      </li>

      <hr class="nav-hr" />

      <li>
        <div class="logout-section-sidenav">
          <a href="{% url 'projects:index' %}">
            <i class="bx bx-exit bx-rotate-180 nav_icon"></i>
            <span class="link_name">Back to Projects</span>
          </a>
          <ul class="sub-menu blank comeback-submenu">
            <li>
              <a class="link_name" href="{% url 'projects:index' %}">Back to Projects</a>
            </li>
          </ul>
        </div>
      </li>
    </ul>
  </div>

  <section class="home-section">
    <div class="home-content fixed-top">
      <i class="bx bx-menu"></i>

      <div class="home-content-right">
        {% if status == 'FINISHED' %}
        <i class='bx bx-check iconsmr'></i>
        <h5 class="h4 fntsmr_scanning">FINISHED</h5>
        {% endif %}
        {% if status == 'SCANNING' %}
        <i class='bx bx-loader-circle loader'></i>
        <h5 class="h4 fntsmr_scanning">SCANNING</h5>
        {% endif %}
        {% if status == 'WAITING' %}
        <i class='bx bxs-hand iconsmr blink_me'></i>
        <h5 class="h4 fntsmr_scanning">WAITING</h5>
        {% endif %}
        <i class="bx bx-globe iconsmr"></i>
        <h5 class="h4 fntsmr_scan_mode">SCAN MODE: <span class="scan_mode">SUBDOMAINS</span></h5>

        <i class="bx bx-target-lock iconsmr"></i>
        <h5 class="h4 fntsmr">{{ title_domain_target }}</h5>

        <!-- <hr class="rftw-vertical-line"> -->

        <div class="action" onmouseover="menuToggle();" onmouseout="menuToggle();">
          <div class="profile">
            <img src="{{ imagePath }}" />
          </div>
          <div class="menu">
            <h3>{{ request.user }}<br /><span>Reconnaissance Ninja</span></h3>
            <ul>
              <li>
                <a href="{% url 'edit_profile:index' %}"><i class="bx bx-sm bx-user-circle"></i>Edit profile</a>
              </li>
              <li>
                <a href="{% url 'apikeys_settings:index' %}"><i class="bx bx-sm bx-cog"></i> API Keys</a>
              </li>
              <li>
                <a href="{% url 'logout' %}"><i class="bx bx-sm bx-log-out-circle"></i> Logout</a>
              </li>
            </ul>
          </div>
        </div>
      </div>
    </div>

    <!-- BODY -->
    <div class="container-fluid">
      <div class="card-body" id="section-1">
        <div class="row">
          <div class="d-sm-flex align-items-center align-to-cards">
            <i class="bx bx-sm bx-globe"></i>
            <p>
              <strong> SUBDOMAINS </strong>
            </p>
          </div>

          <div class="col-xs-6">
            <div class="table-responsive">
              <table id="subdomains" class="table table-striped table-content" style="width: 100%">
                <thead>
                  <tr>
                    <th>#</th>
                    <th>SUBDOMAIN</th>
                    <th>IP ADDRESS</th>
                    <th>PORT</th>
                    <th>SUBDOMAIN TAKEOVER</th>
                  </tr>
                </thead>
                <tbody>
                  {% for subdomains in subdomains_table %}

                  <tr>
                    <td>{{ forloop.counter }}</td>
                    <td>{{ subdomains.subdomain }}</td>
                    <td>{{ subdomains.ip_address }}</td>
                    <td>{{ subdomains.ports }}</td>
                    <td>{{ subdomains.subtakeover }}</td>
                  </tr>

                  {% endfor %}
                </tbody>
              </table>

              <div class="mb-2 mt-3">
                <button class="btn-reconftw" data-target="#modal-dns-zonetransfer" data-toggle="modal">
                  <i class="bx bxs-chevron-up"></i>
                  <span>DNS ZONE TRANSFER</span>
                </button>

                <i class="bx bx-wifi-0"></i>

                <button class="btn-reconftw" data-target="#modal-dns-registry" data-toggle="modal">
                  <i class="bx bxs-chevron-up"></i>
                  <span>DNS REGISTRY</span>
                </button>

                <i class="bx bx-wifi-0"></i>

                <button class="btn-reconftw" data-target="#modal-cms" data-toggle="modal">
                  <i class="bx bxs-chevron-up"></i>
                  <span>CMS</span>
                </button>
              </div>
            </div>
          </div>
        </div>
      </div>

      <hr />

      <div class="card-body" id="section-2">
        <div class="row">
          <div class="d-sm-flex align-items-center align-to-cards" id="#cloud_assets">
            <i class="bx bx-sm bx-cloud"></i>
            <p>
              <strong> CLOUD ASSETS </strong>
            </p>
          </div>

          <div class="col-xs-6">
            <div class="table-content table-responsive">
              <table id="cloud_assets" class="table table-striped" style="width: 100%">
                <thead>
                  <tr>
                    <th>S3 BUCKETS</th>
                    <th>APP FOUND</th>
                    <th>STORAGE ACCOUNT</th>
                    <th>AZURE DNS NAME</th>
                    <th>GOOGLE BUCKET</th>
                  </tr>
                </thead>
                <tbody>
                  {% for cloud_asset in cloud_assets %}
                  <tr>
                    <td>{{ cloud_asset.protected_s3bucket }}</td>
                    <td>{{ cloud_asset.appfound }}</td>
                    <td>{{ cloud_asset.storage_account }}</td>
                    <td>{{ cloud_asset.azure }}</td>
                    <td>{{ cloud_asset.google }}</td>
                  </tr>
                  {% endfor %}
                </tbody>
              </table>
            </div>
          </div>
        </div>
      </div>
    </div>

    <hr />

    <div class="card-body" id="section-3">
      <div class="row">
        <div class="d-sm-flex align-items-center align-to-cards">
          <i class="bx bx-sm bx-image"></i>
          <p>
            <strong> SCREENSHOTS </strong>
          </p>
        </div>

        <div class="col-xs-5">
          <div class="table-responsive">

            <div id="reconftw-gallery" data-nanogallery2='{
                
                "thumbnailWidth": "auto",
                "thumbnailHeight": "400",
                "thumbnailBorderVertical": 0,
                "thumbnailBorderHorizontal": 0,
                "thumbnailDisplayTransitionDuration": 5000,
                "thumbnailLabel": {
                  "position": "overImageOnBottom",
                  "displayDescription": true
                },
                "galleryFilterTags": true,
                "displayBreadcrumb": true,
                "breadcrumbOnlyCurrentLevel": true,
                "thumbnailOpenImage": true,
                "galleryDisplayMode": "pagination",
                "galleryMaxRows": 5,
                "galleryPaginationMode": "numbers",
                "thumbnailAlignment": "center",
                "navPagination": false,
                "galleryFilterTags": "description",
                "thumbnailLevelUp": true
              }'>
              {% for i in screenshots %}
              <a href="data:image/jpeg;base64,{{ i.2 }}" data-ngthumb="data:image/jpeg;base64,{{ i.2 }}"
                data-ngdesc="{{ i.3 }}">{{ i.0 }}</a>
              {% endfor %}
            </div>

          </div>
        </div>
      </div>
    </div>


    </div>
    </div>

    <hr />

    <!-- FOOTER -->
    <footer class="sticky-footer bg-footer">
      <div class="container my-auto">
        <div class="copyright text-center my-auto">
          <span>reconFTW ©</span>
        </div>
      </div>
    </footer>
  </section>

</body>

<!-- </html> N ESQUECER -->
{% endblock %}